### ISSUE TITLE
Search Not working

### ISSUE THREAD

**Issue by FireMasterK** [mautrix/instagram#13]
Logs:
```
2021-06-26 21:45:39,668] [DEBUG@mau.attrs] Failed to deserialize {'pk': 4236812322, 'username': 'elonrmuskk', 'full_name': 'Elon Musk Now', 'is_private': False, 'profile_pic_url': 'https://instagram.fbom26-1.fna.fbcdn.net/v/t51.2885-19/s150x150/44329317_268583430479565_454483638147350528_n.jpg?tp=1&_nc_ht=instagram.fbom26-1.fna.fbcdn.net&_nc_ohc=VmWI97mTacMAX9iRTzq&edm=AM7KJZYBAAAA&ccb=7-4&oh=661e5a7dbf5156beec1a356c319fba3b&oe=60DE6270&_nc_sid=d96ff1', 'profile_pic_id': '1921356713098066787_4236812322', 'is_verified': False, 'follow_friction_type': 0, 'has_anonymous_profile_picture': False, 'account_badges': [], 'social_context': 'Followed by redacted', 'search_social_context': 'Followed by redacted', 'friendship_status': {'following': False, 'is_private': False, 'incoming_request': False, 'outgoing_request': False, 'is_bestie': False, 'is_restricted': False}, 'latest_reel_media': 0, 'live_broadcast_id': None} into SearchResultUser
[2021-06-26 21:45:39,669] [ERROR@mau.commands] Unhandled error while handling command search elonmusk from @kavin:kavin.rocks (ref: 1624743909)
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/mautrix/types/util/serializable_attrs.py", line 188, in _dict_to_attrs
    obj = attrs_type(**new_items)
TypeError: __init__() missing 1 required positional argument: 'mutual_followers_count'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/mautrix/bridge/commands/handler.py", line 406, in handle
    await self._run_handler(handler, evt)
  File "/usr/lib/python3.9/site-packages/mautrix/bridge/commands/handler.py", line 291, in __call__
    return await self._handler(evt)
  File "/usr/lib/python3.9/site-packages/mautrix_instagram/commands/misc.py", line 30, in search
    resp = await evt.sender.client.search_users(" ".join(evt.args))
  File "/opt/mautrix-instagram/mauigpapi/http/user.py", line 27, in search_users
    return await self.std_http_get("/api/v1/users/search/", query=req,
  File "/opt/mautrix-instagram/mauigpapi/http/base.py", line 138, in std_http_get
    return response_type.deserialize(json_data)
  File "/usr/lib/python3.9/site-packages/mautrix/types/util/serializable_attrs.py", line 349, in deserialize
    return _dict_to_attrs(cls, data)
  File "/usr/lib/python3.9/site-packages/mautrix/types/util/serializable_attrs.py", line 176, in _dict_to_attrs
    new_items[name] = _try_deserialize(field, value)
  File "/usr/lib/python3.9/site-packages/mautrix/types/util/serializable_attrs.py", line 204, in _try_deserialize
    return _deserialize(field.type, value, field.default)
  File "/usr/lib/python3.9/site-packages/mautrix/types/util/serializable_attrs.py", line 255, in _deserialize
    return [_deserialize(item_cls, item) for item in value]
  File "/usr/lib/python3.9/site-packages/mautrix/types/util/serializable_attrs.py", line 255, in <listcomp>
    return [_deserialize(item_cls, item) for item in value]
  File "/usr/lib/python3.9/site-packages/mautrix/types/util/serializable_attrs.py", line 242, in _deserialize
    return _dict_to_attrs(cls, value, default, default_if_empty=True)
  File "/usr/lib/python3.9/site-packages/mautrix/types/util/serializable_attrs.py", line 194, in _dict_to_attrs
    raise SerializerError("Missing value for required key "
mautrix.types.util.serializable.SerializerError: Missing value for required key mutual_followers_count in SearchResultUser
```

**Comment by FireMasterK** [comment]
It's been fixed since c035683a89cd2b87c2ea58a038b2fa861aa20c41.
