### ISSUE TITLE
error when running

### ISSUE THREAD

**Issue by Anas-Sherif** [mautrix/instagram#23]
here is the log
```
Nov 22 18:20:20 server python[680955]: [2021-11-22 18:20:20,963] [INFO@mau.init] Initializing mautrix-instagram 0.1.1+dev.a87b1a44
Nov 22 18:20:20 server python[680955]: [2021-11-22 18:20:20,965] [INFO@mau.init] Initialization complete in 0.08 seconds
Nov 22 18:20:20 server python[680955]: [2021-11-22 18:20:20,965] [DEBUG@mau.init] Running startup actions...
Nov 22 18:20:20 server python[680955]: [2021-11-22 18:20:20,966] [DEBUG@mau.db] Connecting to postgres://instagram:[redacted]@127.0.0.1/instagram
Nov 22 18:20:20 server python[680955]: [2021-11-22 18:20:20,966] [CRITICAL@mau.init] Unexpected error in main event loop
Nov 22 18:20:20 server python[680955]: Traceback (most recent call last):
Nov 22 18:20:20 server python[680955]:   File "/opt/mautrix-instagram/lib/python3.9/site-packages/mautrix/util/program.py", line 197, in _run
Nov 22 18:20:20 server python[680955]:     self.loop.run_until_complete(self.start())
Nov 22 18:20:20 server python[680955]:   File "/usr/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
Nov 22 18:20:20 server python[680955]:     return future.result()
Nov 22 18:20:20 server python[680955]:   File "/opt/mautrix-instagram/lib/python3.9/site-packages/mautrix_instagram/__main__.py", line 76, in start
Nov 22 18:20:20 server python[680955]:     await self.db.start()
Nov 22 18:20:20 server python[680955]:   File "/opt/mautrix-instagram/lib/python3.9/site-packages/mautrix/util/async_db/asyncpg.py", line 39, in start
Nov 22 18:20:20 server python[680955]:     self._pool = await asyncpg.create_pool(self.url, **self._db_args)
Nov 22 18:20:20 server python[680955]:   File "/opt/mautrix-instagram/lib/python3.9/site-packages/asyncpg/pool.py", line 407, in _async__init__
Nov 22 18:20:20 server python[680955]:     await self._initialize()
Nov 22 18:20:20 server python[680955]:   File "/opt/mautrix-instagram/lib/python3.9/site-packages/asyncpg/pool.py", line 435, in _initialize
Nov 22 18:20:20 server python[680955]:     await first_ch.connect()
Nov 22 18:20:20 server python[680955]:   File "/opt/mautrix-instagram/lib/python3.9/site-packages/asyncpg/pool.py", line 127, in connect
Nov 22 18:20:20 server python[680955]:     self._con = await self._pool._get_new_connection()
Nov 22 18:20:20 server python[680955]:   File "/opt/mautrix-instagram/lib/python3.9/site-packages/asyncpg/pool.py", line 477, in _get_new_connection
Nov 22 18:20:20 server python[680955]:     con = await connection.connect(
Nov 22 18:20:20 server python[680955]:   File "/opt/mautrix-instagram/lib/python3.9/site-packages/asyncpg/connection.py", line 1981, in connect
Nov 22 18:20:20 server python[680955]:     return await connect_utils._connect(
Nov 22 18:20:20 server python[680955]:   File "/opt/mautrix-instagram/lib/python3.9/site-packages/asyncpg/connect_utils.py", line 725, in _connect
Nov 22 18:20:20 server python[680955]:     addrs, params, config = _parse_connect_arguments(timeout=timeout, **kwargs)
Nov 22 18:20:20 server python[680955]:   File "/opt/mautrix-instagram/lib/python3.9/site-packages/asyncpg/connect_utils.py", line 491, in _parse_connect_arguments
Nov 22 18:20:20 server python[680955]:     addrs, params = _parse_connect_dsn_and_args(
Nov 22 18:20:20 server python[680955]:   File "/opt/mautrix-instagram/lib/python3.9/site-packages/asyncpg/connect_utils.py", line 253, in _parse_connect_dsn_and_args
Nov 22 18:20:20 server python[680955]:     host, port = _parse_hostlist(dsn_hostspec, port, unquote=True)
Nov 22 18:20:20 server python[680955]:   File "/opt/mautrix-instagram/lib/python3.9/site-packages/asyncpg/connect_utils.py", line 213, in _parse_hostlist
Nov 22 18:20:20 server python[680955]:     hostlist_ports.append(int(hostspec_port))
Nov 22 18:20:20 server python[680955]: ValueError: invalid literal for int() with base 10: '!2'
Nov 22 18:20:21 server systemd[1]: mautrix-instagram.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Nov 22 18:20:21 server systemd[1]: mautrix-instagram.service: Failed with result 'exit-code'.
lines 31-73/73 (END)
~~~

**Comment by Anas-Sherif** [comment]
managed to fix it but ran into diffrent error 
```
[2021-11-22 21:48:41,716] [INFO@mau.init] Initializing mautrix-instagram 0.1.1+dev.a87b1a44
[2021-11-22 21:48:41,718] [INFO@mau.init] Initialization complete in 0.1 seconds
[2021-11-22 21:48:41,718] [DEBUG@mau.init] Running startup actions...
[2021-11-22 21:48:41,719] [DEBUG@mau.db] Connecting to postgres://instagram:123789as@127.0.0.1/instagram
[2021-11-22 21:48:41,736] [DEBUG@mau.init] Starting appservice...
[2021-11-22 21:48:41,736] [DEBUG@mau.as] Starting appservice web server on 0.0.0.0:29330
[2021-11-22 21:48:41,736] [INFO@mau.mx] Ensuring connectivity to homeserver
[2021-11-22 21:48:41,844] [ERROR@mau.mx] Connection to homeserver failed, retrying in 10 seconds
Traceback (most recent call last):
  File "/opt/mautrix-instagram/lib/python3.9/site-packages/mautrix/bridge/matrix.py", line 107, in wait_for_connection
    await self.az.intent.whoami()
  File "/opt/mautrix-instagram/lib/python3.9/site-packages/mautrix/client/api/authentication.py", line 154, in whoami
    resp = await self.api.request(Method.GET, Path.account.whoami)
  File "/opt/mautrix-instagram/lib/python3.9/site-packages/mautrix/api.py", line 259, in request
    return await self._send(method, full_url, content, query_params, headers or {})
  File "/opt/mautrix-instagram/lib/python3.9/site-packages/mautrix/api.py", line 180, in _send
    raise make_request_error(http_status=response.status,
mautrix.errors.request.MUnknownToken: Invalid macaroon passed.
```

**Comment by borisgrigorov** [comment]
How did you solve the problem, please?

**Comment by Anas-Sherif** [comment]
> How did you solve the problem, please?

I don't remember but I've switched to docker since it's easier to set up.

**Comment by borisgrigorov** [comment]
Yes, it happens to me in docker, but anyway, thank you.
