### ISSUE TITLE
Missing value for required key is_pin in Thread error on login

### ISSUE THREAD

**Issue by uumas** [mautrix/instagram#26]
When trying to login to the bridge it says successfully logged in, gets my name and instagram sends me an email saying a new device has logged in but `ping` tells me MQTT not connected. Running `connect` gives this:

```
Traceback (most recent call last):
  File "/opt/mautrix-instagram/lib/python3.7/site-packages/mautrix/types/util/serializable_attrs.py", line 194, in _dict_to_attrs
    obj = attrs_type(**new_items)
TypeError: __init__() missing 1 required keyword-only argument: 'is_pin'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/mautrix-instagram/lib/python3.7/site-packages/mautrix/bridge/commands/handler.py", line 409, in handle
    await self._run_handler(handler, evt)
  File "/opt/mautrix-instagram/lib/python3.7/site-packages/mautrix/bridge/commands/handler.py", line 296, in __call__
    return await self._handler(evt)
  File "/opt/mautrix-instagram/lib/python3.7/site-packages/mautrix_instagram/commands/conn.py", line 70, in connect
    await evt.sender.refresh(resync=False)
  File "/opt/mautrix-instagram/lib/python3.7/site-packages/mautrix_instagram/user.py", line 255, in refresh
    await self.start_listen()
  File "/opt/mautrix-instagram/lib/python3.7/site-packages/mautrix_instagram/user.py", line 295, in start_listen
    resp = await self.client.get_inbox(limit=1)
  File "/opt/mautrix-instagram/lib/python3.7/site-packages/mauigpapi/http/thread.py", line 39, in get_inbox
    response_type=DMInboxResponse)
  File "/opt/mautrix-instagram/lib/python3.7/site-packages/mauigpapi/http/base.py", line 138, in std_http_get
    return response_type.deserialize(json_data)
  File "/opt/mautrix-instagram/lib/python3.7/site-packages/mautrix/types/util/serializable_attrs.py", line 354, in deserialize
    return _dict_to_attrs(cls, data)
  File "/opt/mautrix-instagram/lib/python3.7/site-packages/mautrix/types/util/serializable_attrs.py", line 182, in _dict_to_attrs
    new_items[name] = _try_deserialize(field_meta, value)
  File "/opt/mautrix-instagram/lib/python3.7/site-packages/mautrix/types/util/serializable_attrs.py", line 210, in _try_deserialize
    return _deserialize(field.type, value, field.default)
  File "/opt/mautrix-instagram/lib/python3.7/site-packages/mautrix/types/util/serializable_attrs.py", line 248, in _deserialize
    return _dict_to_attrs(cls, value, default, default_if_empty=True)
  File "/opt/mautrix-instagram/lib/python3.7/site-packages/mautrix/types/util/serializable_attrs.py", line 182, in _dict_to_attrs
    new_items[name] = _try_deserialize(field_meta, value)
  File "/opt/mautrix-instagram/lib/python3.7/site-packages/mautrix/types/util/serializable_attrs.py", line 210, in _try_deserialize
    return _deserialize(field.type, value, field.default)
  File "/opt/mautrix-instagram/lib/python3.7/site-packages/mautrix/types/util/serializable_attrs.py", line 261, in _deserialize
    return [_deserialize(item_cls, item) for item in value]
  File "/opt/mautrix-instagram/lib/python3.7/site-packages/mautrix/types/util/serializable_attrs.py", line 261, in <listcomp>
    return [_deserialize(item_cls, item) for item in value]
  File "/opt/mautrix-instagram/lib/python3.7/site-packages/mautrix/types/util/serializable_attrs.py", line 248, in _deserialize
    return _dict_to_attrs(cls, value, default, default_if_empty=True)
  File "/opt/mautrix-instagram/lib/python3.7/site-packages/mautrix/types/util/serializable_attrs.py", line 201, in _dict_to_attrs
    f"{json_key} in {attrs_type.__name__}") from e
mautrix.types.util.serializable.SerializerError: Missing value for required key is_pin in Thread
```

The same error appeared in the bridge log when initially logging in but wasn't reported in the management room.

**Comment by tulir** [comment]
This seems to have been fixed already in https://github.com/mautrix/instagram/commit/85265c3fb747ef7c81c2573126a326d554ef074b

**Comment by uumas** [comment]
ah, there hasn't been a pypi release since august. Will there be one soon or should I just use master for now?
