### ISSUE TITLE
Can't send PNG images but JPEG works

### ISSUE THREAD

**Issue by jizyy6c1s** [mautrix/instagram#41]
Homeserver: Conduit 0.2.0
Clients tried: nheko 0.9.1 and Element 1.9.8
Versions tried: release 0.1.2, `0.1.2+dev.0c955be3`, `0.1.2+dev.245e8a20`

When I try to send a PNG image, the bridge says, "⚠ Your message was not bridged: 'NoneType' object has no attribute 'open'" and I see this error in the logs:
```
Jan 28 00:38:25 server mautrix_instagram[24560]: [2022-01-28 00:38:25,326] [INFO@aiohttp.access] 127.0.0.1 [28/Jan/2022:00:38:25 +0000] "PUT /_matrix/app/v1/transactions/MZ%2D0Q2gDdct85%2D[room]?access_token=[token] HTTP/1.1" 200 158 "-" "-"
Jan 28 00:38:25 server mautrix_instagram[24560]: [2022-01-28 00:38:25,328] [DEBUG@mau.mx] Received Matrix event $53PDD39z_VuAHI9F7VSxQxe1EdoNhxf6qPW762025lg from @user:server.com in ![room]:server.com
Jan 28 00:38:25 server mautrix_instagram[24560]: [2022-01-28 00:38:25,330] [DEBUG@mau.portal.[insert id]] Handling Matrix message $53PDD39z_VuAHI9F7VSxQxe1EdoNhxf6qPW762025lg from @user:server.com/[my id] with request ID 6892626872965858786
Jan 28 00:38:25 server mautrix_instagram[24560]: [2022-01-28 00:38:25,347] [ERROR@mau.portal.[insert id]] Fatal error handling Matrix event $53PDD39z_VuAHI9F7VSxQxe1EdoNhxf6qPW762025lg: 'NoneType' object has no attribute 'open'
Jan 28 00:38:25 server mautrix_instagram[24560]: Traceback (most recent call last):
Jan 28 00:38:25 server mautrix_instagram[24560]:   File "/home/instagram_bridge/instagram/lib/python3.7/site-packages/mautrix_instagram/portal.py", line 275, in handle_matrix_message
Jan 28 00:38:25 server mautrix_instagram[24560]:     await self._handle_matrix_message(sender, message, event_id)
Jan 28 00:38:25 server mautrix_instagram[24560]:   File "/home/instagram_bridge/instagram/lib/python3.7/site-packages/mautrix_instagram/portal.py", line 428, in _handle_matrix_message
Jan 28 00:38:25 server mautrix_instagram[24560]:     height=message.info.height,
Jan 28 00:38:25 server mautrix_instagram[24560]:   File "/home/instagram_bridge/instagram/lib/python3.7/site-packages/mautrix_instagram/portal.py", line 300, in _handle_matrix_image
Jan 28 00:38:25 server mautrix_instagram[24560]:     img = Image.open(inp)
Jan 28 00:38:25 server mautrix_instagram[24560]: AttributeError: 'NoneType' object has no attribute 'open'
Jan 28 00:38:25 server mautrix_instagram[24560]: [2022-01-28 00:38:25,421] [INFO@aiohttp.access] 127.0.0.1 [28/Jan/2022:00:38:25 +0000] "PUT /_matrix/app/v1/transactions/YfKDjl1m6SpwoeNgq3e%2D[room]?access_token=[token] HTTP/1.1" 200 158 "-" "-"
```
(my apologies if I have redacted too much information, I have a copy if anything important is missing)
However, if I send a JPEG image it works fine and sends:
```
Jan 28 00:51:26 server mautrix_instagram[24560]: [2022-01-28 00:51:26,605] [DEBUG@mau.mx] Received Matrix event $GCUEOkYHZ8d7NhHImp_kQk7SLIEC7fzZZSbusxt4r0A from @user:server.com in ![room]:server.com
Jan 28 00:51:26 server mautrix_instagram[24560]: [2022-01-28 00:51:26,606] [DEBUG@mau.portal.[id]] Handling Matrix message $GCUEOkYHZ8d7NhHImp_kQk7SLIEC7fzZZSbusxt4r0A from @user:server.com/[my id] with request ID 6892630149877530901
Jan 28 00:51:29 server mautrix_instagram[24560]: [2022-01-28 00:51:29,658] [DEBUG@mau.portal.[id]] Ignoring message 30314108036079811630835115560534016 (6892630149877530901) by [my id] as it was sent by us (client_context in dedup queue)
Jan 28 00:51:29 server mautrix_instagram[24560]: [2022-01-28 00:51:29,989] [DEBUG@mau.portal.[id]] Handled Matrix message $GCUEOkYHZ8d7NhHImp_kQk7SLIEC7fzZZSbusxt4r0A (6892630149877530901) -> 30314108036079811630835115560534016
```
I'm guessing the conversion from PNG -> JPEG is failing?
Thanks in advance to anyone who helps :)

**Comment by jizyy6c1s** [comment]
Uhh, I took out lines 289-303 and both JPEGs and PNGs work now! I'm not sure if this is good enough for a PR, or it's a quick hack that will break something else.
![image](https://user-images.githubusercontent.com/30058021/151596099-e258b8f1-6d00-48db-a3fe-4071792af41a.png)
