### ISSUE TITLE
Sharing video to Instagram fails with "Transcode not finished yet"

### ISSUE THREAD

**Issue by tamcore** [mautrix/instagram#47]
Sharing a short video to a bridged room results in the error bellow. As the upload process itself seems to be successful, maybe this should be something that's retried after a few seconds.

````
[TRACE@mau.instagram.http.@philipp:pborn.eu] /api/v1/direct_v2/threads/broadcast/configure_video/ response: {"message":"Transcode not finished yet.","status":"fail"}
[ERROR@mau.portal.34028236......0446384892] Fatal error handling Matrix event $x4aYkMtXjPfyI3aI7wf2NaQde4xoMU54t4UT4H5qthQ: Request POST /api/v1/direct_v2/threads/broadcast/configure_video/ failed: Transcode not finished yet.
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/mautrix_instagram/portal.py", line 276, in handle_matrix_message
    await self._handle_matrix_message(sender, message, event_id)
  File "/usr/lib/python3.9/site-packages/mautrix_instagram/portal.py", line 452, in _handle_matrix_message
    resp = await self._handle_matrix_video(
  File "/usr/lib/python3.9/site-packages/mautrix_instagram/portal.py", line 348, in _handle_matrix_video
    return await sender.client.broadcast(
  File "/opt/mautrix-instagram/mauigpapi/http/thread.py", line 152, in broadcast
    return await self._broadcast(
  File "/opt/mautrix-instagram/mauigpapi/http/thread.py", line 137, in _broadcast
    return await self.std_http_post(
  File "/opt/mautrix-instagram/mauigpapi/http/base.py", line 151, in std_http_post
    json_data = await self._handle_response(resp)
  File "/opt/mautrix-instagram/mauigpapi/http/base.py", line 181, in _handle_response
    await self._raise_response_error(resp)
  File "/opt/mautrix-instagram/mauigpapi/http/base.py", line 223, in _raise_response_error
    raise IGResponseError(resp, data)
mauigpapi.errors.response.IGResponseError: Request POST /api/v1/direct_v2/threads/broadcast/configure_video/ failed: Transcode not finished yet.
````

**Comment by vlourme** [comment]
I have the same issue, almost every video I tried to send gets this error.
I tried to debug and compare with other libraries and I don't see the issue, my guess is an encoding parameters error.

Furthermore, I'll continue debugging and do a PR if I find something.
