### ISSUE TITLE
Error while connecting to Instagram

### ISSUE THREAD

**Issue by Joni-Samanen** [mautrix/instagram#62]
fresh install on a private synapse server. I can succesfully log in, but get instantly logged out. Here's the traceback:

Traceback (most recent call last):
  File "/opt/mautrix-instagram/lib/python3.9/site-packages/mautrix/types/util/serializable_attrs.py", line 212, in _dict_to_attrs
    obj = attrs_type(**new_items)
TypeError: __init__() missing 1 required keyword-only argument: 'biography_product_mentions'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/mautrix-instagram/lib/python3.9/site-packages/mautrix_instagram/user.py", line 181, in try_connect
    await self.connect()
  File "/opt/mautrix-instagram/lib/python3.9/site-packages/mautrix_instagram/user.py", line 204, in connect
    resp = await client.current_user()
  File "/opt/mautrix-instagram/lib/python3.9/site-packages/mauigpapi/http/account.py", line 29, in current_user
    return await self.std_http_get(
  File "/opt/mautrix-instagram/lib/python3.9/site-packages/mauigpapi/http/base.py", line 177, in std_http_get
    return response_type.deserialize(json_data)
  File "/opt/mautrix-instagram/lib/python3.9/site-packages/mautrix/types/util/serializable_attrs.py", line 375, in deserialize
    return _dict_to_attrs(cls, data)
  File "/opt/mautrix-instagram/lib/python3.9/site-packages/mautrix/types/util/serializable_attrs.py", line 198, in _dict_to_attrs
    new_items[name] = _try_deserialize(field_meta, value)
  File "/opt/mautrix-instagram/lib/python3.9/site-packages/mautrix/types/util/serializable_attrs.py", line 229, in _try_deserialize
    return _deserialize(field.type, value, field.default)
  File "/opt/mautrix-instagram/lib/python3.9/site-packages/mautrix/types/util/serializable_attrs.py", line 267, in _deserialize
    return _dict_to_attrs(cls, value, default, default_if_empty=True)
  File "/opt/mautrix-instagram/lib/python3.9/site-packages/mautrix/types/util/serializable_attrs.py", line 218, in _dict_to_attrs
    raise SerializerError(
mautrix.types.util.serializable.SerializerError: Missing value for required key biography_product_mentions in CurrentUser

Let me know if I can provide any more meaningful troubleshoot info.

**Comment by Joni-Samanen** [comment]
I didn't look for the closed issues at first. I saw from there that we should use latest for now. That fixed the issue indeed. Sorry for bothering.
