### ISSUE TITLE
Challenge required on login

### ISSUE THREAD

**Issue by immanuelfodor** [mautrix/instagram#68]
I logged out in the bridge, changed IG password on the web, then logged in on the web without any error, then tried to log in with the bridge, and I get this error every time:

```
Unhandled error while handling command:
```
```
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/mautrix_instagram/commands/auth.py", line 77, in login
    resp = await api.login(username, password)
  File "/opt/mautrix-instagram/mauigpapi/http/login.py", line 58, in login
    return await self.std_http_post(
  File "/opt/mautrix-instagram/mauigpapi/http/base.py", line 158, in std_http_post
    json_data = await self._handle_response(resp)
  File "/opt/mautrix-instagram/mauigpapi/http/base.py", line 191, in _handle_response
    await self._raise_response_error(resp)
  File "/opt/mautrix-instagram/mauigpapi/http/base.py", line 213, in _raise_response_error
    raise err
mauigpapi.errors.response.IGChallengeError: Request POST /api/v1/accounts/login/ failed: challenge_required

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/mautrix/bridge/commands/handler.py", line 491, in handle
    await self._run_handler(handler, evt)
  File "/usr/lib/python3.10/site-packages/mautrix/bridge/commands/handler.py", line 340, in __call__
    return await self._handler(evt)
  File "/usr/lib/python3.10/site-packages/mautrix_instagram/commands/auth.py", line 100, in login
    await api.challenge_auto(reset=True)
  File "/opt/mautrix-instagram/mauigpapi/http/challenge.py", line 107, in challenge_auto
    challenge = self.state.challenge or await self.challenge_get_state()
  File "/opt/mautrix-instagram/mauigpapi/http/challenge.py", line 35, in challenge_get_state
    await self.std_http_get(self.__path, query=query, response_type=ChallengeStateResponse)
  File "/opt/mautrix-instagram/mauigpapi/http/challenge.py", line 26, in __path
    return f"/api/v1{self.state.challenge_path}"
  File "/opt/mautrix-instagram/mauigpapi/state/state.py", line 77, in challenge_path
    raise IGNoChallengeError()
mauigpapi.errors.state.IGNoChallengeError: No challenge data available
```

After it happens, I need to accept a "was this you" screen on the web:

![Screenshot_2022-11-30_12-54-59](https://user-images.githubusercontent.com/21174107/204790822-72e103db-20db-4093-a9a3-54b783b5f519.png)

I suppose this is what the bridge is presented, too, and so it can't login. Maybe the screen is different from what the bridge expects, so that's why there is "no challenge data available" or I don't know.

**Comment by tulir** [comment]
Challenges are not supported in the bridge anymore, use real 2-factor auth

**Comment by immanuelfodor** [comment]
For anyone who wants to set up 2FA:
- You can only set up SMS at first if you haven't had the Instagram app installed for a while on your mobile. The web Instagram only allows SMS 2FA to be turned on and tells you that auth app 2FA can only be enabled from the Insta app. When you install the Insta app and try to set up auth app 2FA, it tells you that you need to wait a few days to enable it. Weird, so you need to stick to SMS 2FA for a while.
- While you have an active login session in the Insta app, you won't receive 2FA codes in SMS but you get a notification in the Insta app to approve a new login. Since the bridge requires the code, your only choice is to log out of the app to receive the SMS code. You can log back to the Insta app again to be able to wait out the few days required to auth app 2FA to be available (hopefully).

**Comment by tulir** [comment]
You can use the `resend-sms` command when it asks for the SMS code if you don't get the code the first time (just added a mention of that to the 2fa prompt message)

**Comment by yspreen** [comment]
@tulir okay but with the newest version of the bridge, and with 2FA on my account, I still got the challenge today.

After accepting the challenge on my phone I had to log into the bridge again and then it worked without the code.

The challenge to me doesn't correlate with 2FA
