### ISSUE TITLE
Application service has not registered this user

### ISSUE THREAD

**Issue by Severin-S** [mautrix/instagram#72]
Probably related to #71.
After a restart (and update to `mautrix-instagram 0.2.3+dev.6f40e012`) of the bridge I found another exception. Like in #71 it occurred during thread sync, but this time it raises a different error.
```
[2022-12-16 19:50:12,802] [ERROR@mau.user.@severin:schueller.xyz] Failed to sync threads. Waiting 30 seconds before retrying sync.
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/mautrix_instagram/user.py", line 823, in run_with_sync_lock
    await func()
  File "/usr/lib/python3.10/site-packages/mautrix_instagram/user.py", line 760, in _backfill_threads
    await self._sync_threads_with_delay(
  File "/usr/lib/python3.10/site-packages/mautrix_instagram/user.py", line 796, in _sync_threads_with_delay
    had_new_messages = await self._sync_thread(thread)
  File "/usr/lib/python3.10/site-packages/mautrix_instagram/user.py", line 604, in _sync_thread
    base_insertion_event_id = await portal.backfill_message_page(
  File "/usr/lib/python3.10/site-packages/mautrix_instagram/portal.py", line 2166, in backfill_message_page
    batch_send_resp = await self.main_intent.batch_send(
  File "/usr/lib/python3.10/site-packages/mautrix/appservice/api/intent.py", line 536, in batch_send
    resp = await self.api.request(
  File "/usr/lib/python3.10/site-packages/mautrix/api.py", line 401, in request
    resp_data, resp = await self._send(
  File "/usr/lib/python3.10/site-packages/mautrix/api.py", line 256, in _send
    raise make_request_error(
mautrix.errors.request.MForbidden: Application service has not registered this user (@instagram_ID:schueller.xyz)
```

**Comment by sumnerevans** [comment]
Synapse's implementation of `batch_send` is full of bugs and undefined behavior, so I'm not even sure if this is a bug in the bridge.
